### ISSUE TITLE
 Provide a function to `src.web.main` to clean all files.

### ISSUE THREAD

**Issue by lunaflight** [lunaflight/courserekt#22]
**Describe the problem**
Cached files found in `web/static/pages/` should be deletable from the python script, but it is not.

**Describe the feature**
Expose a subcommand like `clean` in `src.web.main` which deletes the cached files.

**Comment by stridefox** [comment]
Hi, I'm new here. The folder called `web/static/pages` cannot be found in the static folder. Could you please provide further clarification?

**Comment by lunaflight** [comment]
Upon running `python -m src.web.main` or `./scripts/main.sh`, it will precompute all pages and cache it in that directory. See the following line of code https://github.com/lunaflight/courserekt/blob/444300077a34716866e41aeffb5652cdbc8a8e14/src/web/precomp.py#L48

**Comment by stridefox** [comment]
@lunaflight, I have tried to run the instructions in CONTRIBUTING.md. I am getting the following error when I try to run `python -m src.web.main`:-
```
[14:56:33] (INFO) src.history:build:     Converting PDFs to CSVs...
[14:56:33] (INFO) src.history:build:     Please be patient. This might take some time.
[14:56:33] (CRITICAL) src.history:build:         exc = [WinError 3] The system cannot find the path specified
Traceback (most recent call last):
  File "D:\Rohan S Gurumurthy\Coding\Python\Development\OpenSource\courserekt\src\history\build.py", line 38, in build
    convert_pdfs_fn(run_args)
  File "D:\Rohan S Gurumurthy\Coding\Python\Development\OpenSource\courserekt\src\history\convert_pdfs.py", line 39, in convert        
    shutil.copy2(pdf_file, Path(TMP_DIRECTORY) / new_filename)
  File "C:\Python312\Lib\shutil.py", line 460, in copy2
    _winapi.CopyFile2(src_, dst_, flags)
FileNotFoundError: [WinError 3] The system cannot find the path specified
```

**Comment by lunaflight** [comment]
Hmm, looks frustrating. I admit that I haven't done any development on Windows and can only guarantee that it works on Mac / Linux. You can try using WSL2 or something similar to work in a linux environment here.

This is because all the directories are coded with the assumption that you are working in a linux environment. This could be another thing to look into, as referenced in this related issue as well https://github.com/lunaflight/courserekt/issues/23. Going forward, I should make it clear if Windows is supported or not in the docs.

**Comment by SpookyYomo** [comment]
@lunaflight Traceback references the error pertaining to 
https://github.com/lunaflight/courserekt/blob/444300077a34716866e41aeffb5652cdbc8a8e14/src/history/convert_pdfs.py#L39
I suspect `/` (in contrast to use of `joinpath`) or `||` (as created in https://github.com/lunaflight/courserekt/blob/444300077a34716866e41aeffb5652cdbc8a8e14/src/history/convert_pdfs.py#L30) might be mangling with Windoze (`|` is a forbidden character for filenames), `joinpath` is the canonical method to append to Path objects.
Also me wondering why specifically `shutil`?

@stridefox Please consider using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). There are plenty of online tutorials on how to go about to install WSL. This project has strong assumption that the user is on POSIX-compliant system, but we've only tested to Linux and MacOS, with BASH as the shell in the documentation. Please feel free to open a bug report if the issue persists for you within WSL.

**Comment by lunaflight** [comment]
That sounds like the problem. Feel free to make a PR to make this work on windows - I can test for correctness on linux. 
About `shutil`, no particular reason here.
